package com.adobe.communities.ugc.management.commons;

/**
 * Created by mokatari on 10/13/17.
 */
public enum ComponentEnum {
    BLOG_ENTRY, BLOG_COMMENT, FORUM_ENTRY, FORUM_COMMENT,
    CALENDAR_EVENT, CALENDAR_COMMENT, QNA_POST, QNA_TOPIC,
    FILE_LIBRARY_FOLDER, FILE_LIBRARY_DOCUMENT, IDEATION_IDEA,
    IDEATION_COMMENT, TALLY_VOTING, TALLY_RATING, TALLY_LIKING, ACTIVITY_STREAMS
}
